# Generated by Django 2.2.2 on 2019-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daytask',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Learning'), ('2', 'English'), ('3', 'Research')], max_length=1)),
                ('content', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'Learning'), ('2', 'English'), ('3', 'Research')], max_length=1)),
                ('creator', models.CharField(max_length=255)),
                ('createtime', models.DateField()),
                ('stime', models.DateField()),
                ('etime', models.DateField()),
                ('content', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
    ]
