# Generated by Django 2.2.2 on 2019-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_auto_20190622_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytask',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
