# Generated by Django 2.2.2 on 2019-06-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_auto_20190622_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytask',
            old_name='id',
            new_name='dtid',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='tid',
        ),
        migrations.AddField(
            model_name='daytask',
            name='taskid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mis.Task'),
            preserve_default=False,
        ),
    ]
