# Generated by Django 2.2.2 on 2019-06-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_auto_20190622_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytask',
            old_name='taskid',
            new_name='task',
        ),
    ]
