# Generated by Django 2.2.2 on 2019-06-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0005_auto_20190622_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnFinishedTask',
            fields=[
                ('uftid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('left_days', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Task')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedTask',
            fields=[
                ('ftid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('passed_days', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Task')),
            ],
        ),
    ]
